### ISSUE TITLE
Can anyone please provide the steps for cross compiling the rauc-hawkbit-updater on raspberrypi with the aarch64?

### ISSUE THREAD

**Issue by surabhiashok1** [rauc/rauc-hawkbit-updater#132]

**Comment by Bastian-Krause** [comment]
https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html

But you should rather use a build system, e.g. [Yocto]() or [ptxdist](https://git.pengutronix.de/cgit/ptxdist/tree/rules/rauc-hawkbit-updater.make).

Please use a recent build system and toolchain version, as you were already told in  https://github.com/rauc/meta-rauc/issues/222 and #131.
