### ISSUE TITLE
Rauc hawkbit, azure docker container returns 301

### ISSUE THREAD

**Issue by CaidenKehrer** [rauc/rauc-hawkbit-updater#133]
We have set up hawkbit in azure app services using an app service https certificate. 

We also have this as our rauc manifest config. 

>   [client]
  hawkbit_server            = myserver.com
  ssl                       = true
  ssl_verify                = false
  tenant_id                 = DEFAULT
  target_name               = 127086
  auth_token                = token
  bundle_download_location  = /mnt/data/rauc/bundle.raucb
  retry_wait                = 60
  connect_timeout           = 20
  timeout                   = 60
  log_level                 = debug
  post_update_reboot        = true
  [device]
  product                   = aps400a
  model                     = aps400a
  serialnumber              = 127086
  hw_revision               = 1

When we run `sudo rauc-hawkbit-updater -c /mnt/data/hawkbit.conf -r --debug`

The server response body comes back as
> DEBUG: Response body: {
  "config" : {
    "polling" : {
      "sleep" : "00:05:00"
    }
  },
  "_links" : {
    "deploymentBase" : {
      "href" : "http://myserver.com/DEFAULT/controller/v1/127086/deploymentBase/6?c=416217484"
    }
  }
}

and then says 
> WARNING: HTTP request failed: 301; server response:

Are we missing a toggle that needs to be set? When we turn off forced HTTPS and SSL it is able to do the download however when we turn it back on we get the error 301.

**Comment by adamwendel** [comment]
co-worker here. issue was actually in the application.properties in hawkbit. needed to set the following:
`hawkbit.artifact.url.protocols.download-http.protocol=https
server.forward-headers-strategy=NATIVE`
