### ISSUE TITLE
Compilation doesn't work since change to meson

### ISSUE THREAD

**Issue by lreinecke** [rauc/rauc-hawkbit-updater#141]
I am trying to compile this code, but everytime I run `meson setup build` ther is an error `ERROR: Neither directory contains a build file meson.build.`. I use this command in the base folder of the project `.../rauc-hawkbit-updater/`. Do you know how to fix this?

I use a crosscompiler. With cmake it worked fine. This schould not be a problem with meson?

**Comment by Bastian-Krause** [comment]
Very strange. Could you please post the complete output of these commands?

```
$ rm -rf build
$ git status
$ git show -s
$ ls -la
$ meson setup --debug --wipe build
```

**Comment by lreinecke** [comment]
I tried a bit with your commands. This was the result:
![Console Output 1](https://user-images.githubusercontent.com/96118883/196444663-9ef3a983-1c03-4eb7-91d5-5785de0b92ae.PNG)
![Console Output 2](https://user-images.githubusercontent.com/96118883/196444741-1a1e218c-cf22-4b54-affc-8a40a897094f.PNG)
![Console Output 3](https://user-images.githubusercontent.com/96118883/196445044-5e60b71d-bce5-4885-a44f-47f900c45a48.PNG)
The `git show -s` resulted in this:
![git show -s](https://user-images.githubusercontent.com/96118883/196445226-2977ca90-af83-4d49-ab80-41fbd1c031ba.PNG)

**Comment by Bastian-Krause** [comment]
What version of meson are you using? Is there a wrapper around your meson or is it called directly?

You could add "strace" before meson to see where it's actually looking for the meson.build. But if these basic operations do not work as intended, I don't have high hopes that everything works as expected if this error is gone..

**Comment by lreinecke** [comment]
It worked fine, without the crosscompiler. So its a problem with the crosscompiler, and not with your code.

**Comment by Bastian-Krause** [comment]
Yes, I suspected that.

**Comment by lreinecke** [comment]
Thanks for your time. I suppose I have to solve this problem fo my own.

**Comment by Bastian-Krause** [comment]
If the solution might help others, please post it here. Thanks.

**Comment by eli-schwartz** [comment]
> but everytime I run `meson setup build` ther is an error `ERROR: Neither directory contains a build file meson.build.`. I use this command in the base folder of the project `.../rauc-hawkbit-updater/`. Do you know how to fix this?

The two directories in question that "neither" contains a build file `meson.build` are either:
- the current working directory
- `build/`
or else, for versions of Meson before 0.42 (when `meson setup` was introduced):
- `setup/`
- `build/`

I believe it is vanishingly unlikely you are using versions of Meson older than 0.42, but at the same time you've strongly indicated that `ls` reports a meson.build file.

So it's probable that your cross compiler is actually overwriting the definition of the `meson` program, but posting the output of `type -a meson` (bash or zsh) or `whence -ca ls` (optional for zsh) could help clarify that.

**Comment by lreinecke** [comment]
The meson of my crosscompiler is version 0.53.2
There is an `meson.build` file in the base directory of the project where it should be.
If I only type `meson setup` or `meson build` it finds the `meson.build` but throws the Error `ERROR: Unable to determine dynamic linker`
If I use `strace` it shows, that it looks only in the subdirectories `setup/` and `build/` for the file. There are none and so it fails.

**Comment by lreinecke** [comment]
@eli-schwartz @Bastian-Krause I have found a solution for (all of) my problems. My crosscompiler overwrites the PATH variable in a way that it used a meson-binary with the version 0.53.2. This version didn't work for me. So i had to use the local meson by typing `/usr/bin/meson setup build --cross-file meson.cross`. Then it works fine.
