### ISSUE TITLE
Transfer any file to the target board using Rauc-hawkbit-updater

### ISSUE THREAD

**Issue by SGEMBEDDED** [rauc/rauc-hawkbit-updater#153]
How can i transfer any binary file into target board using Hawkbit Tool?

Actually i am able to send the rauc bundles from the PC to the target board. And it is successfully installing the rauc bundles in the board, but when i am trying to send any file(binay file) into the target board it is not visible and also rauc-hawkbit-updater is trying to install that file. 

I only want to send a simple binary file into target board.  If it is possible then please share the answers for my query.

Thankyou

**Comment by Bastian-Krause** [comment]
rauc-hawkbit-updater (hence the name) is only meant to download a RAUC bundle from hawkBit (or pass information to RAUC to stream it) **and** install it. There is no way to skip the installation step. If the binary file you're transferring is not part of the bundle, rauc-hawkbit-updater is not the right tool for your task.
