### ISSUE TITLE
Doesn't support rauc configured without dbus

### ISSUE THREAD

**Issue by diorcety** [rauc/rauc-hawkbit-updater#157]
Currently rauc-hawkbit-updater doesn't support rauc when configured without dbus (--disable-service)

**Comment by Bastian-Krause** [comment]
This is correct and expected, see the first paragraph in our README:
https://github.com/rauc/rauc-hawkbit-updater/blob/c5e2091db3dff9e6fc49066f0eb8a87a3c931d9b/README.md?plain=1#L11-L15
