### ISSUE TITLE
Moving Repository to 'rauc' GitHub Organization?

### ISSUE THREAD

**Issue by ejoerns** [rauc/rauc-hawkbit-updater#18]
Hi,

as this piece of software seems to raise more and more interest for people that look for a non-python alternative of https://github.com/rauc/rauc-hawkbit and do not want to reinvent the wheel, I would like to ask you if you are interested in moving the repository to the rauc organization on GitHub. This could give the project even more attention and makes it visibly belonging to RAUC.

We also plan to integrate this into meta-rauc and would like to clarify a future-proof location before ;)

Thus, if you are interested, we could move the repository keeping all issues etc intact and add you (@prevas-lkmi and other if desired) as maintainer for the project's team.

Would be great if you let me know which variant you prefer. If you have any concerns or questions, just let me know.

Best regards, Enrico

**Comment by prevas-lkmi** [comment]
Hi Enrico

I see no problem in moving the repository to the RAUC organization, as long I get to be one of the maintainers. I would prefer to move the repository with all issues etc. if it is possible.

-Lasse

**Comment by Raphexion** [comment]
I don't mind being a maintainer. You guys can decide.

**Comment by ejoerns** [comment]
@prevas-lkmi Great to hear that, first of all and thanks for your reply!

Yes, transferring will preserve all the issues etc. And the idea is that you, and those of you that would like to can become or remain maintainers (and GitHub Collaborators) of the repo.

For actually transferring the repository it would be required to give me Administrator Collaborator rights on your repository. This can be done via 'Settings'->'Collaborators & Teams'. 
If we understood GitHub's permission handling correctly, then I should be allowed to transfer the repository.

Any concerns or questions regarding this?

**Comment by prevas-lkmi** [comment]
> @prevas-lkmi Great to hear that, first of all and thanks for your reply!
> 
> Yes, transferring will preserve all the issues etc. And the idea is that you, and those of you that would like to can become or remain maintainers (and GitHub Collaborators) of the repo.
> 
> For actually transferring the repository it would be required to give me Administrator Collaborator rights on your repository. This can be done via 'Settings'->'Collaborators & Teams'.
> If we understood GitHub's permission handling correctly, then I should be allowed to transfer the repository.
> 
> Any concerns or questions regarding this?

**Comment by prevas-lkmi** [comment]
@ejoerns I have added you as admin now.

**Comment by ejoerns** [comment]
:+1: let's move!

**Comment by ejoerns** [comment]
And... welcome to rauc!

**Comment by ejoerns** [comment]
I'd assume this can be closed now ;)
