### ISSUE TITLE
Segmentation fault caused by "config.conf" file

### ISSUE THREAD

**Issue by ctenruh-phytec** [rauc/rauc-hawkbit-updater#23]
Hi,
when using the rauc-hawkbit-updater, we get a SIGSEGV. Segmentation Fault.
We noticed, that the updater crashes while trying to get the data from the “config.conf” file.
It seems, that the Boolean variables in the “config.conf” file are not parsed correctly and because of that the comments, which are declared with a “#” on the same line, are being ignored as comments and written into the variables.

Did anyone have the same Problem?

Thanks.

**Comment by ejoerns** [comment]
Comments (in the same line) are not (really) supported by the parser, yes.

Maybe we should remove them from the example, but it should work fine without them @ctenruh-phytec, isn't it?

In any way, it should not segfault for a broken config :)

**Comment by ctenruh-phytec** [comment]
it works fine when the comments are removed. I will create a pull request for this issue with the edited config file.
