### ISSUE TITLE
json_root not released in hawkbit_pull_cb

### ISSUE THREAD

**Issue by hpatriarche** [rauc/rauc-hawkbit-updater#36]
in function `static gboolean hawkbit_pull_cb(gpointer user_data)`
JsonNode *json_root = json_parser_get_root(json_response_parser);
but it is not unref.

+g_object_unref(json_root);
g_object_unref(json_response_parser);

**Comment by prevas-lkmi** [comment]
The documentation says the root node is owned by the parser, and you are not allowed to free it.

**Comment by hpatriarche** [comment]
ok, then
