### ISSUE TITLE
Curl Follow Location

### ISSUE THREAD

**Issue by hpatriarche** [rauc/rauc-hawkbit-updater#40]
Hi,

In our version, we added 
`curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);`

is it an option that make sense by default ?

**Comment by jluebbe** [comment]
We have that in rauc's network code as well. So I'd say yes...

**Comment by Raphexion** [comment]
I think it makes a lot of sense. Is there any risk adding this?

**Comment by ejoerns** [comment]
Many projects set this [1], thus I don't see why we shouldn't.
I'd expect location following to be the common default and not following it only for specific reasons.
The reasons it is not the default in libcurl to my knowledge is only that the libcurl default way is to have almost everything turned off unless explicitly enabled.
As documentation and examples state, this should be used together with setting `CURLOPT_MAXREDIRS` to a low number (most use `5` here).

[1] https://codesearch.debian.net/search?q=CURLOPT_FOLLOWLOCATION&literal=1
