### ISSUE TITLE
rauc-hawkbit-updater failed when dbus is restarted

### ISSUE THREAD

**Issue by hpatriarche** [rauc/rauc-hawkbit-updater#42]
According to my testing, `rauc-hawkbit-upater` failed when dbus process is restarted.

`rauc-hawkbit-updater.service` should also set statement:
```
After=rauc.service dbus.socket
Requires=rauc.service dbus.socket
```
in order to restart in case rauc or dbus failure

**Comment by ejoerns** [comment]
@hpatriarche As RAUC can be started via D-Bus activation, it should not be necessary to require the rauc.service. Maybe `After` is sufficient?

**Comment by ejoerns** [comment]
Any update on this? Ist that resolved?
