### ISSUE TITLE
hawkbit-client.c: memory leak on debug messages 

### ISSUE THREAD

**Issue by rfuentess** [rauc/rauc-hawkbit-updater#45]
hawkbit-client. c is making use of `json_to_string()` for debugging messages ([1](https://github.com/rauc/rauc-hawkbit-updater/blob/master/src/hawkbit-client.c#L641), [2](https://github.com/rauc/rauc-hawkbit-updater/blob/master/src/hawkbit-client.c#L750)). However, this is provoking a small leak as said function returns a `char *` that must be released manually. 

A possible fix could be:

```c
char *str = json_to_string(resp_root, TRUE);
g_debug("Deployment response: %s\n", str);
free(str);
```

If this approach is OK, we can proceed to generate a PR :)

**Comment by ejoerns** [comment]
@rfuentess You're right, this is still an issue.

I'd suggest making use of autofree as we already do in other locations, too. Thus something like

``` c
g_autofree gchar *str = json_to_string(resp_root, TRUE);
g_debug("Deployment response: %s\n", str);
```

**Comment by rfuentess** [comment]
I'm new to this macro.  But because `gchar` is an alias for `char`  I think we are going to be fine :)
I'll run some tests just to be sure and then I'll proceed to generate the PR
