### ISSUE TITLE
Update .gitignore for the temporary files generated by uncrustify

### ISSUE THREAD

**Issue by rfuentess** [rauc/rauc-hawkbit-updater#57]
Hi, 

I was playing with the code a little when I run `uncrustify.sh` to guarantee the your code convention. That is when I noticed that uncrustify leftovers are not ignored. Not a big deal, but if one is lazy at the moment of calling `git add` we may end with trash on the commits, wasting time on the PR reviews .

As a mitigation, `.gitignore` may be updated  to include the following lines: 
```
# Backup files done by uncrustify
.uncrustify/
*~
```

**Comment by ejoerns** [comment]
Sound good, seems I missed that when porting the script from the rauc repo (there we have the .gitignore line), would you like to make a PR with that?
